default: &default
  allpay:
    merchant_id: 2000132 # 官方的測試 id、key 與 iv
    hash_key: 5294y06JbISpM5x9
    hash_iv: v77hoKGq4kWxNNIS
    trade_desc: 築優教育測試
    return_url: http://api.zu-edu.com/allpay/callback
    mode: :test

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  # allpay:
  #   merchant_id: <%= ENV['ALLPAY_MERCHANT_ID'] %>
  #   hash_key: <%= ENV['ALLPAY_HASH_KEY'] %>
  #   hash_iv: <%= ENV['ALLPAY_HASH_IV'] %>
  #   trade_desc: 築優教育
  #   return_url: http://api.zu-edu.com/allpay/callback
  #   mode: :production
